### ISSUE TITLE
最新版幻海有问题

### ISSUE THREAD

**Issue by Cheney0120** [Natsukage/Fishers-Intuition#11]
你好，我本来是在nga下载的release版，后续发现幻海倒计时不刷新，然后想着自己拉下源码看了下，因为不是很会c#所以测试不一定严谨，但是我看这应该是特殊天气的代码应该没问题，我试图去用云冠群岛的特殊天气做测试，也是可以正常倒计时的，但是在幻海中又碰到了新bug，进入幻海后所有提示全部消失了，只有上钩之后有一下提示，包括咬钩计时和幻海倒计时都没有，我去debug发现WeatherCheck方法获取当前海域剩余时间时会抛异常
![QQ_1721927162855](https://github.com/user-attachments/assets/6c01b584-b064-4309-9300-0e07c643d190)

![QQ_1721927122737](https://github.com/user-attachments/assets/3ad1bfbd-45d7-4320-8300-21a4a6572ff1)

![QQ_1721926770228](https://github.com/user-attachments/assets/09a5f0a4-4551-4095-955d-d127b8c90ed2)

想问一下该怎么修改该地址还是偏移量

**Comment by Natsukage** [comment]
啊，因为我其实已经弃坑挺久了，所以对于现在最新版本的sig逻辑我也是不清楚的，所以也帮不上什么忙（
很抱歉，最近几次的更新其实都是其他人提交的pr，我自己其实相当于是什么都没做过（
NGA的release版本其实挺古老了，正常来说最新的编译版应该是在Action里的最新版。但是如果你拉了源码自己调试存在问题的话，那Action的版本肯定也存在同样的问题（Action里的版本就是基于最新源码的自动编译）

**Comment by Cheney0120** [comment]
好的，还是非常感谢你的回复，我去学习一下相关逻辑看看能不能自己改一下

**Comment by Cheney0120** [comment]
issue我先不关闭了，我看能不能改了再关，如果这几天改不好了我再关闭，非常感谢
